// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/hansenhalim/elelibrary/be/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookSearcher creates a new instance of MockBookSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookSearcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBookSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBookSearcher is an autogenerated mock type for the BookSearcher type
type MockBookSearcher struct {
	mock.Mock
}

type MockBookSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookSearcher) EXPECT() *MockBookSearcher_Expecter {
	return &MockBookSearcher_Expecter{mock: &_m.Mock}
}

// SearchBooks provides a mock function for the type MockBookSearcher
func (_mock *MockBookSearcher) SearchBooks(ctx context.Context, query string, offset int, limit int) ([]entity.Book, error) {
	ret := _mock.Called(ctx, query, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchBooks")
	}

	var r0 []entity.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entity.Book, error)); ok {
		return returnFunc(ctx, query, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []entity.Book); ok {
		r0 = returnFunc(ctx, query, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, query, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookSearcher_SearchBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchBooks'
type MockBookSearcher_SearchBooks_Call struct {
	*mock.Call
}

// SearchBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - offset int
//   - limit int
func (_e *MockBookSearcher_Expecter) SearchBooks(ctx any, query any, offset any, limit any) *MockBookSearcher_SearchBooks_Call {
	return &MockBookSearcher_SearchBooks_Call{Call: _e.mock.On("SearchBooks", ctx, query, offset, limit)}
}

func (_c *MockBookSearcher_SearchBooks_Call) Run(run func(ctx context.Context, query string, offset int, limit int)) *MockBookSearcher_SearchBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookSearcher_SearchBooks_Call) Return(books []entity.Book, err error) *MockBookSearcher_SearchBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockBookSearcher_SearchBooks_Call) RunAndReturn(run func(ctx context.Context, query string, offset int, limit int) ([]entity.Book, error)) *MockBookSearcher_SearchBooks_Call {
	_c.Call.Return(run)
	return _c
}
