// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/hansenhalim/elelibrary/be/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFavoriteAdder creates a new instance of MockFavoriteAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteAdder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFavoriteAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFavoriteAdder is an autogenerated mock type for the FavoriteAdder type
type MockFavoriteAdder struct {
	mock.Mock
}

type MockFavoriteAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteAdder) EXPECT() *MockFavoriteAdder_Expecter {
	return &MockFavoriteAdder_Expecter{mock: &_m.Mock}
}

// AddFavorite provides a mock function for the type MockFavoriteAdder
func (_mock *MockFavoriteAdder) AddFavorite(ctx context.Context, bookID string) error {
	ret := _mock.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for AddFavorite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFavoriteAdder_AddFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFavorite'
type MockFavoriteAdder_AddFavorite_Call struct {
	*mock.Call
}

// AddFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
func (_e *MockFavoriteAdder_Expecter) AddFavorite(ctx any, bookID any) *MockFavoriteAdder_AddFavorite_Call {
	return &MockFavoriteAdder_AddFavorite_Call{Call: _e.mock.On("AddFavorite", ctx, bookID)}
}

func (_c *MockFavoriteAdder_AddFavorite_Call) Run(run func(ctx context.Context, bookID string)) *MockFavoriteAdder_AddFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteAdder_AddFavorite_Call) Return(err error) *MockFavoriteAdder_AddFavorite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFavoriteAdder_AddFavorite_Call) RunAndReturn(run func(ctx context.Context, bookID string) error) *MockFavoriteAdder_AddFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookSearcher creates a new instance of MockBookSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookSearcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBookSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBookSearcher is an autogenerated mock type for the BookSearcher type
type MockBookSearcher struct {
	mock.Mock
}

type MockBookSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookSearcher) EXPECT() *MockBookSearcher_Expecter {
	return &MockBookSearcher_Expecter{mock: &_m.Mock}
}

// SearchBooks provides a mock function for the type MockBookSearcher
func (_mock *MockBookSearcher) SearchBooks(ctx context.Context, query string, offset int, limit int) ([]entity.Book, error) {
	ret := _mock.Called(ctx, query, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchBooks")
	}

	var r0 []entity.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entity.Book, error)); ok {
		return returnFunc(ctx, query, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []entity.Book); ok {
		r0 = returnFunc(ctx, query, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, query, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookSearcher_SearchBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchBooks'
type MockBookSearcher_SearchBooks_Call struct {
	*mock.Call
}

// SearchBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - offset int
//   - limit int
func (_e *MockBookSearcher_Expecter) SearchBooks(ctx any, query any, offset any, limit any) *MockBookSearcher_SearchBooks_Call {
	return &MockBookSearcher_SearchBooks_Call{Call: _e.mock.On("SearchBooks", ctx, query, offset, limit)}
}

func (_c *MockBookSearcher_SearchBooks_Call) Run(run func(ctx context.Context, query string, offset int, limit int)) *MockBookSearcher_SearchBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookSearcher_SearchBooks_Call) Return(books []entity.Book, err error) *MockBookSearcher_SearchBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockBookSearcher_SearchBooks_Call) RunAndReturn(run func(ctx context.Context, query string, offset int, limit int) ([]entity.Book, error)) *MockBookSearcher_SearchBooks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFavoriteFinder creates a new instance of MockFavoriteFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteFinder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFavoriteFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFavoriteFinder is an autogenerated mock type for the FavoriteFinder type
type MockFavoriteFinder struct {
	mock.Mock
}

type MockFavoriteFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteFinder) EXPECT() *MockFavoriteFinder_Expecter {
	return &MockFavoriteFinder_Expecter{mock: &_m.Mock}
}

// FindFavoriteIDs provides a mock function for the type MockFavoriteFinder
func (_mock *MockFavoriteFinder) FindFavoriteIDs(ctx context.Context, bookIDs []string) ([]string, error) {
	ret := _mock.Called(ctx, bookIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindFavoriteIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(ctx, bookIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(ctx, bookIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, bookIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteFinder_FindFavoriteIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFavoriteIDs'
type MockFavoriteFinder_FindFavoriteIDs_Call struct {
	*mock.Call
}

// FindFavoriteIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - bookIDs []string
func (_e *MockFavoriteFinder_Expecter) FindFavoriteIDs(ctx any, bookIDs any) *MockFavoriteFinder_FindFavoriteIDs_Call {
	return &MockFavoriteFinder_FindFavoriteIDs_Call{Call: _e.mock.On("FindFavoriteIDs", ctx, bookIDs)}
}

func (_c *MockFavoriteFinder_FindFavoriteIDs_Call) Run(run func(ctx context.Context, bookIDs []string)) *MockFavoriteFinder_FindFavoriteIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteFinder_FindFavoriteIDs_Call) Return(strings []string, err error) *MockFavoriteFinder_FindFavoriteIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFavoriteFinder_FindFavoriteIDs_Call) RunAndReturn(run func(ctx context.Context, bookIDs []string) ([]string, error)) *MockFavoriteFinder_FindFavoriteIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFavoriteRemover creates a new instance of MockFavoriteRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteRemover {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFavoriteRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFavoriteRemover is an autogenerated mock type for the FavoriteRemover type
type MockFavoriteRemover struct {
	mock.Mock
}

type MockFavoriteRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteRemover) EXPECT() *MockFavoriteRemover_Expecter {
	return &MockFavoriteRemover_Expecter{mock: &_m.Mock}
}

// RemoveFavorite provides a mock function for the type MockFavoriteRemover
func (_mock *MockFavoriteRemover) RemoveFavorite(ctx context.Context, bookID string) error {
	ret := _mock.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFavorite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFavoriteRemover_RemoveFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFavorite'
type MockFavoriteRemover_RemoveFavorite_Call struct {
	*mock.Call
}

// RemoveFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
func (_e *MockFavoriteRemover_Expecter) RemoveFavorite(ctx any, bookID any) *MockFavoriteRemover_RemoveFavorite_Call {
	return &MockFavoriteRemover_RemoveFavorite_Call{Call: _e.mock.On("RemoveFavorite", ctx, bookID)}
}

func (_c *MockFavoriteRemover_RemoveFavorite_Call) Run(run func(ctx context.Context, bookID string)) *MockFavoriteRemover_RemoveFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteRemover_RemoveFavorite_Call) Return(err error) *MockFavoriteRemover_RemoveFavorite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFavoriteRemover_RemoveFavorite_Call) RunAndReturn(run func(ctx context.Context, bookID string) error) *MockFavoriteRemover_RemoveFavorite_Call {
	_c.Call.Return(run)
	return _c
}
